name: milmujeres_app
description: "A app for Mil Mujeres"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^9.0.0
  carousel_slider: ^5.0.0
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.8.0
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  flutter_html: ^3.0.0
  intl: any
  latlong2: ^0.9.1
  responsive_framework: ^1.5.1
  responsive_grid: ^2.4.4
  url_launcher: ^6.3.1
  file_picker: ^10.2.0
  location: ^5.0.0
  shared_preferences: ^2.2.2
  video_player: ^2.10.0
  video_player_web: ^2.3.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  # Launcher icon
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

# Launcher icon config
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 18 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/splash.png
  #branding: assets/splash/branding.png
  android: true
  ios: true
  web: true

  android_12:
    image: assets/icon/icon.png
    icon_background_color: "#ffffff"
    # image_dark: assets/logo-acceptance.png
    # icon_background_color_dark: "#121212"


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/banners/
    - assets/images/mm-actions/
    - assets/images/rating/
    - assets/images/
    - assets/icon/
    - assets/splash/
    - .env