class Deposit {
  Deposit({
    required this.id,
    required this.userId,
    required this.clientId,
    required this.caaseId,
    required this.applicationId,
    required this.taskId,
    required this.officeId,
    required this.firstDeposit,
    required this.emailSent,
    required this.emailSentTo,
    required this.emailDate,
    required this.scheduledUserId,
    required this.scheduledCommission,
    required this.scheduledCommissionAmount,
    required this.depositUserId,
    required this.depositCommission,
    required this.depositCommissionAmount,
    required this.newClientLanguageAndScheduledCommission,
    required this.newClientLanguageAndScheduledAmount,
    required this.totalCommissionAmount,
    required this.checked,
    required this.paymentMethodId,
    required this.depositTypeId,
    required this.paymentDate,
    required this.paymentCreditCardHow,
    required this.creditCardPersonName,
    required this.englishFees,
    required this.frenchFees,
    required this.therapyFees,
    required this.mmFees,
    required this.mexicanDeptOfProtection,
    required this.fundraisingEvent,
    required this.grants,
    required this.clientReimbursements,
    required this.other,
    required this.explanationForOther,
    required this.notesOrServicesPaid,
    required this.uscisFeesReceived,
    required this.mmCheckNumber,
    required this.personWhoWroteTheCheck,
    required this.createdAt,
    required this.updatedAt,
    required this.caase,
    required this.depositPaymentUser,
    required this.depositScheduledUser,
    required this.depositType,
    required this.office,
    required this.user,
    required this.paymentMethod,
  });

  String id;
  String userId;
  String clientId;
  String caaseId;
  String applicationId;
  String taskId;
  String officeId;
  String firstDeposit;
  String emailSent;
  String emailSentTo;
  String emailDate;
  String scheduledUserId;
  String scheduledCommission;
  String scheduledCommissionAmount;
  String depositUserId;
  String depositCommission;
  String depositCommissionAmount;
  String newClientLanguageAndScheduledCommission;
  String newClientLanguageAndScheduledAmount;
  String totalCommissionAmount;
  String checked;
  String paymentMethodId;
  String depositTypeId;
  String paymentDate;
  String paymentCreditCardHow;
  String creditCardPersonName;
  String englishFees;
  String frenchFees;
  String therapyFees;
  String mmFees;
  String mexicanDeptOfProtection;
  String fundraisingEvent;
  String grants;
  String clientReimbursements;
  String other;
  String explanationForOther;
  String notesOrServicesPaid;
  String uscisFeesReceived;
  String mmCheckNumber;
  String personWhoWroteTheCheck;
  String createdAt;
  String updatedAt;
  var caase;
  var depositPaymentUser;
  var depositScheduledUser;
  var depositType;
  var office;
  var user;
  var paymentMethod;

  factory Deposit.fromJson(Map<String, dynamic> json) => Deposit(
    id: json["id"].toString(),
    userId: json["user_id"].toString(),
    clientId: json["client_id"].toString(),
    caaseId: json["caase_id"].toString(),
    applicationId: json["application_id"].toString(),
    taskId: json["task_id"].toString(),
    officeId: json["office_id"].toString(),
    firstDeposit: json["first_deposit"].toString(),
    emailSent: json["email_sent"].toString(),
    emailSentTo: json["email_sent_to"].toString(),
    emailDate: json["email_date"].toString(),
    scheduledUserId: json["scheduled_user_id"].toString(),
    scheduledCommission: json["scheduled_commission"].toString(),
    scheduledCommissionAmount: json["scheduled_commission_amount"].toString(),
    depositUserId: json["deposit_user_id"].toString(),
    depositCommission: json["deposit_commission"].toString(),
    depositCommissionAmount: json["deposit_commission_amount"].toString(),
    newClientLanguageAndScheduledCommission:
        json["new_client_language_and_scheduled_commission"].toString(),
    newClientLanguageAndScheduledAmount:
        json["new_client_language_and_scheduled_amount"].toString(),
    totalCommissionAmount: json["total_commission_amount"].toString(),
    checked: json["checked"].toString(),
    paymentMethodId: json["payment_method_id"].toString(),
    depositTypeId: json["deposit_type_id"].toString(),
    paymentDate: json["payment_date"].toString(),
    paymentCreditCardHow: json["payment_credit_card_how"].toString(),
    creditCardPersonName: json["credit_card_person_name"].toString(),
    englishFees: json["english_fees"].toString(),
    frenchFees: json["french_fees"].toString(),
    therapyFees: json["therapy_fees"].toString(),
    mmFees: json["mm_fees"].toString(),
    mexicanDeptOfProtection: json["mexican_dept_of_protection"].toString(),
    fundraisingEvent: json["fundraising_event"].toString(),
    grants: json["grants"].toString(),
    clientReimbursements: json["client_reimbursements"].toString(),
    other: json["other"].toString(),
    explanationForOther: json["explanation_for_other"].toString(),
    notesOrServicesPaid: json["notes_or_services_paid"].toString(),
    uscisFeesReceived: json["uscis_fees_received"].toString(),
    mmCheckNumber: json["mm_check_number"].toString(),
    personWhoWroteTheCheck: json["person_who_wrote_the_check"].toString(),
    createdAt: json["created_at"].toString(),
    updatedAt: json["updated_at"].toString(),
    caase: json["caase"],
    depositPaymentUser: json["deposit_payment_user"],
    depositScheduledUser: json["deposit_scheduled_user"],
    depositType: json["deposit_type"],
    office: json["office"],
    user: json["user"],
    paymentMethod: json["payment_method"],
  );

  Map<String, dynamic> toJson() => {
    "id": id,
    "user_id": userId,
    "client_id": clientId,
    "caase_id": caaseId,
    "application_id": applicationId,
    "task_id": taskId,
    "office_id": officeId,
    "first_deposit": firstDeposit,
    "email_sent": emailSent,
    "email_sent_to": emailSentTo,
    "email_date": emailDate,
    "scheduled_user_id": scheduledUserId,
    "scheduled_commission": scheduledCommission,
    "scheduled_commission_amount": scheduledCommissionAmount,
    "deposit_user_id": depositUserId,
    "deposit_commission": depositCommission,
    "deposit_commission_amount": depositCommissionAmount,
    "new_client_language_and_scheduled_commission":
        newClientLanguageAndScheduledCommission,
    "new_client_language_and_scheduled_amount":
        newClientLanguageAndScheduledAmount,
    "total_commission_amount": totalCommissionAmount,
    "checked": checked,
    "payment_method_id": paymentMethodId,
    "deposit_type_id": depositTypeId,
    "payment_date": paymentDate,
    "payment_credit_card_how": paymentCreditCardHow,
    "credit_card_person_name": creditCardPersonName,
    "english_fees": englishFees,
    "french_fees": frenchFees,
    "therapy_fees": therapyFees,
    "mm_fees": mmFees,
    "mexican_dept_of_protection": mexicanDeptOfProtection,
    "fundraising_event": fundraisingEvent,
    "grants": grants,
    "client_reimbursements": clientReimbursements,
    "other": other,
    "explanation_for_other": explanationForOther,
    "notes_or_services_paid": notesOrServicesPaid,
    "uscis_fees_received": uscisFeesReceived,
    "mm_check_number": mmCheckNumber,
    "person_who_wrote_the_check": personWhoWroteTheCheck,
    "created_at": createdAt,
    "updated_at": updatedAt,
    "caase": caase,
    "deposit_payment_user": depositPaymentUser,
    "deposit_scheduled_user": depositScheduledUser,
    "deposit_type": depositType,
    "office": office,
    "user": user,
    "payment_method": paymentMethod,
  };
}
