// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxgMbYJKPdDkggl122vnnm71GfiiHSf3A',
    appId: '1:340479106342:web:5004474dafb5c9df3c75e7',
    messagingSenderId: '340479106342',
    projectId: 'milmujeres-notifications-25ed8',
    authDomain: 'milmujeres-notifications-25ed8.firebaseapp.com',
    storageBucket: 'milmujeres-notifications-25ed8.firebasestorage.app',
    measurementId: 'G-CMQ8WQPE9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-v40q6AiOELH8mP6W5v2O-WBR67Xn-c',
    appId: '1:340479106342:android:927a4cf0d7125a153c75e7',
    messagingSenderId: '340479106342',
    projectId: 'milmujeres-notifications-25ed8',
    storageBucket: 'milmujeres-notifications-25ed8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFpNFgfV_Qha4md1IMdnxsgVeo0EUnzgA',
    appId: '1:340479106342:ios:8eb79dd2de0d47ca3c75e7',
    messagingSenderId: '340479106342',
    projectId: 'milmujeres-notifications-25ed8',
    storageBucket: 'milmujeres-notifications-25ed8.firebasestorage.app',
    iosBundleId: 'org.milmujeres.appMilMujeres',
  );

}