// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1GaxWVS2AydYe3NdVvC2VXFm5x7SWt0M',
    appId: '1:602641968223:web:9231bcd4ee34bb43417fea',
    messagingSenderId: '602641968223',
    projectId: 'milmujeres-notifications',
    authDomain: 'milmujeres-notifications.firebaseapp.com',
    storageBucket: 'milmujeres-notifications.firebasestorage.app',
    measurementId: 'G-N0162XTX5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA03dP3KXEfgvGqqghdNgNZLp_w92J5n_s',
    appId: '1:602641968223:android:b89354d7e004322d417fea',
    messagingSenderId: '602641968223',
    projectId: 'milmujeres-notifications',
    storageBucket: 'milmujeres-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ZVIBeZgZdC8ghkgNsf3e_YxTtM4e-SU',
    appId: '1:602641968223:ios:7454698de0b65b46417fea',
    messagingSenderId: '602641968223',
    projectId: 'milmujeres-notifications',
    storageBucket: 'milmujeres-notifications.firebasestorage.app',
    iosBundleId: 'org.milmujeres.appMilMujeres',
  );

}