name: Upload ZIP to Google Drive

on:
  workflow_dispatch:     # Para ejecución manual
  schedule:
    - cron: '59 4 * * 4'  # Jueves a las 11:59 p.m. hora Perú (UTC-5)

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar zip y comprimir archivos
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
          zip -r archive.zip .

      - name: Verificar existencia de archive.zip
        run: |
          if [ ! -f archive.zip ]; then
            echo "❌ El archivo archive.zip no fue creado"
            exit 1
          else
            echo "✅ archive.zip encontrado. Tamaño: $(du -h archive.zip | cut -f1)"
          fi

      - name: Instalar dependencias de Node.js
        run: npm install googleapis

      - name: Subir a Google Drive
        env:
          CLIENT_ID: ${{ secrets.GOOGLE_DRIVE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.GOOGLE_DRIVE_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.GOOGLE_DRIVE_REFRESH_TOKEN }}
          FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        run: |
          node .github/scripts/upload-drive.js
